const formData = {
  success: true,
  message: "Form fields listed successfully",
  result: {
    form_page: {
      id: 1,
      page_number: "1",
      title: "First Page",
    },
    form_fields: [
      {
        id: 1,
        label: "Full Name",
        field_name: "full_name",
        field_type: "text",
        is_required: true,
        options: [],
        order: 1,
      },
      {
        id: 2,
        label: "Date of Birth",
        field_name: "date_of_birth",
        field_type: "date",
        is_required: true,
        options: [],
        order: 2,
      },
      {
        id: 3,
        label: "Number of Children",
        field_name: "number_of_children",
        field_type: "number",
        is_required: false,
        options: [],
        order: 3,
      },
      {
        id: 4,
        label: "Demo Month",
        field_name: "demo_month",
        field_type: "month",
        is_required: false,
        options: [],
        order: 4,
      },
      {
        id: 5,
        label: "Demo Time",
        field_name: "demo_time",
        field_type: "time",
        is_required: false,
        options: [],
        order: 5,
      },
      {
        id: 7,
        label: "Favorite Games",
        field_name: "favorite_games",
        field_type: "checkbox",
        is_required: false,
        options: ["Game 1", "Game 2", "Game 3"],
        order: 6,
      },
      {
        id: 8,
        label: "Gender",
        field_name: "gender",
        field_type: "radio",
        is_required: false,
        options: ["Male", "Female", "Other"],
        order: 7,
      },
      {
        id: 9,
        label: "Country",
        field_name: "country",
        field_type: "dropdown",
        is_required: false,
        options: ["BD", "IN", "UK"],
        order: 8,
      },
      {
        id: 10,
        label: "Profile Image",
        field_name: "profile_image",
        field_type: "file",
        is_required: false,
        options: [],
        order: 9,
      },
      {
        id: 11,
        label: "Educational Qualification",
        field_name: "educational_qualification",
        field_type: "table_group",
        is_required: false,
        options: [
          {
            id: "46d9b94c-e016-47b0-bf0e-4d8c9d0f581c",
            label: "Exam",
            order: "1",
            options: ["SSC", "HSC"],
            field_name: "exam",
            field_type: "dropdown",
            is_required: "0",
            placeholder: "Your Age.",
          },
          {
            id: "0de75f77-34c9-4f7b-891d-4dd280eed3eb",
            label: "GPA",
            order: "1",
            options: [],
            field_name: "gpa",
            field_type: "number",
            is_required: "0",
            placeholder: "___ GPA.",
          },
          {
            id: "dca7b250-6150-4a57-bf15-f12dccbcb49d",
            label: "Board",
            order: "3",
            options: [],
            field_name: "board",
            field_type: "text",
            is_required: "1",
            placeholder: null,
          },
        ],
        order: 10,
      },
      {
        id: 12,
        label: "Guarantor Information",
        field_name: "guarantor_information",
        field_type: "section_group",
        is_required: false,
        options: [
          {
            id: "6fa79918-9fff-4083-88a7-771ba0eeb994",
            label: "Guarantor Name",
            order: "1",
            options: [],
            field_name: "guarantor_name",
            field_type: "text",
            is_required: "1",
          },
          {
            id: "5b1fcaab-c9d5-4db2-9538-b14824392cdd",
            label: "Guarantor NID",
            order: "2",
            options: [],
            field_name: "guarantor_nid",
            field_type: "number",
            is_required: "0",
          },
          {
            id: "6d198dd8-1122-4b99-b1fd-c83d6d6145ad",
            label: "Date of Birth",
            order: "3",
            options: [],
            field_name: "date_of_birth",
            field_type: "date",
            is_required: "1",
          },
          {
            id: "fb776439-a293-4551-b40a-779f4ee0e492",
            label: "Guarantor Profession",
            order: "5",
            options: ["Option 1", "Option 2", "Option 3"],
            field_name: "guarantor_profession",
            field_type: "dropdown",
            is_required: "0",
          },
          {
            id: "04876de2-17e9-401a-b50e-b7d6fd1d9f65",
            label: "Profile Image",
            order: "5",
            options: [],
            field_name: "profile_image",
            field_type: "file",
            is_required: "1",
          },
        ],
        order: 11,
      },
      {
        id: 13,
        label: "Notes",
        field_name: "paragraph",
        field_type: "paragraph",
        is_required: false,
        options: [
          "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        ],
        order: 12,
      },
    ],
  },
};

export default formData;
