export const schoolsList = [
  {
    name: "A. T. Still University of Health Sciences",
    state: "Missouri",
    country: "United States",
  },
  {
    name: "Adelphi University - AU",
    state: "New York",
    country: "United States",
  },
  {
    name: "Albany College of Pharmacy and Health Sciences",
    state: "New York",
    country: "United States",
  },
  {
    name: "Albany Medical College",
    state: "North Carolina",
    country: "United States",
  },
  { name: "Allen College", state: "Iowa", country: "United States" },
  { name: "American University", state: "DC", country: "United States" },
  { name: "Amherst College", state: "Massachusetts", country: "United States" },
  {
    name: "Appalachian State University",
    state: "North Carolina",
    country: "United States",
  },
  {
    name: "Arcadia University",
    state: "Pennsylvania",
    country: "United States",
  },
  {
    name: "Arizona State University",
    state: "Arizona",
    country: "United States",
  },
  { name: "University of Toronto", state: "Ontario", country: "Canada" },
  { name: "McGill University", state: "Quebec", country: "Canada" },
  {
    name: "University of British Columbia",
    state: "British Columbia",
    country: "Canada",
  },
  { name: "Queen's University", state: "Ontario", country: "Canada" },
  { name: "York University", state: "Ontario", country: "Canada" },
  {
    name: "Harvard University",
    state: "Massachusetts",
    country: "United States",
  },
  {
    name: "Stanford University",
    state: "California",
    country: "United States",
  },
  {
    name: "University of Chicago",
    state: "Illinois",
    country: "United States",
  },
  {
    name: "Princeton University",
    state: "New Jersey",
    country: "United States",
  },
  { name: "Yale University", state: "Connecticut", country: "United States" },
  {
    name: "University of Michigan",
    state: "Michigan",
    country: "United States",
  },
  {
    name: "University of Texas at Austin",
    state: "Texas",
    country: "United States",
  },
  { name: "University of Florida", state: "Florida", country: "United States" },
  {
    name: "University of Washington",
    state: "Washington",
    country: "United States",
  },
  {
    name: "University of California, Berkeley",
    state: "California",
    country: "United States",
  },
  { name: "University of Waterloo", state: "Ontario", country: "Canada" },
  { name: "Carleton University", state: "Ontario", country: "Canada" },
  { name: "Dalhousie University", state: "Nova Scotia", country: "Canada" },
  { name: "University of Alberta", state: "Alberta", country: "Canada" },
  {
    name: "Simon Fraser University",
    state: "British Columbia",
    country: "Canada",
  },
  { name: "University of Calgary", state: "Alberta", country: "Canada" },
  {
    name: "Boston University",
    state: "Massachusetts",
    country: "United States",
  },
  {
    name: "Duke University",
    state: "North Carolina",
    country: "United States",
  },
  { name: "Rice University", state: "Texas", country: "United States" },
  {
    name: "Vanderbilt University",
    state: "Tennessee",
    country: "United States",
  },
  {
    name: "University of Virginia",
    state: "Virginia",
    country: "United States",
  },
  { name: "University of Georgia", state: "Georgia", country: "United States" },
  { name: "University of Manitoba", state: "Manitoba", country: "Canada" },
  {
    name: "University of Saskatchewan",
    state: "Saskatchewan",
    country: "Canada",
  },
  { name: "University of Montreal", state: "Quebec", country: "Canada" },
  { name: "Laval University", state: "Quebec", country: "Canada" },
  { name: "University of Ottawa", state: "Ontario", country: "Canada" },
  { name: "Western University", state: "Ontario", country: "Canada" },
  {
    name: "University of Minnesota",
    state: "Minnesota",
    country: "United States",
  },
  {
    name: "University of Colorado Boulder",
    state: "Colorado",
    country: "United States",
  },
  {
    name: "University of Wisconsin-Madison",
    state: "Wisconsin",
    country: "United States",
  },
  { name: "Georgetown University", state: "DC", country: "United States" },
  { name: "Purdue University", state: "Indiana", country: "United States" },
  {
    name: "Indiana University Bloomington",
    state: "Indiana",
    country: "United States",
  },
  {
    name: "University Bloomington New",
    state: "Indiana",
    country: "United States",
  },
];
